### ISSUE TITLE
Upload releases to github?

### ISSUE THREAD

**Issue by monkeymaximus** [usineur/opentitus#2]
Hi! Any chance you'd be able to upload your releases to github so they show up in the releases section? 

Thank you!

**Comment by usineur** [comment]
The links to the VPKs given in the README always match the latest revision.

**Comment by monkeymaximus** [comment]
@usineur - This would help us maintain your homebrew @ http://store.brewology.com/vita/homebrew.php?category=Games

Any chance you would consider using it?
