### ISSUE TITLE
Releases to Github

### ISSUE THREAD

**Issue by monkeymaximus** [usineur/opentitus#3]
Sorry to open another ticket. I replied on the other thread but not sure if Github gives you notifications once they are closed.

@usineur - If you would be willing to upload releases to Github, this would help us maintain your homebrew @ http://store.brewology.com/vita/homebrew.php?category=Games

Any chance you would consider using it? Thanks for your time!

**Comment by usineur** [comment]
Done for ZeldaROTH, Zelda3T and OpenTitus. I close.

**Comment by monkeymaximus** [comment]
@usineur - you are awesome! Thank you!!!!
